# RAGAS
To evaluate answer quality, I am going to generate question answer pairs using openai api

In [5]:
# Cell 1: Imports and setup
from pathlib import Path
from langchain_community.document_loaders import DirectoryLoader
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from dotenv import load_dotenv
import os
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
import random
random.seed(69)

In [ ]:
load_dotenv()

PROJECT_ROOT = Path("C:/Users/filip/Desktop/Thesis/project")
DATA_DIR = PROJECT_ROOT / "data"

In [4]:
# Loads  chunks as LangChain documents
# Using the already-chunked data rather than raw PDFs since RAGAS should generate questions from what the pipeline actually retrieves



embedding_model = HuggingFaceEmbeddings(
    model_name="BAAI/bge-base-en-v1.5",
    model_kwargs={"device": "cpu"}
)

vectorstore = Chroma(
    persist_directory=str(DATA_DIR / "chromadb"),
    collection_name="recursive_100",#typo of 1000
    embedding_function=embedding_model
)

# Get all documents from the collection
all_docs = vectorstore.get()
print(f"Loaded {len(all_docs['documents'])} chunks")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4856.67it/s]
BertModel LOAD REPORT from: BAAI/bge-base-en-v1.5
Key                     | Status     | Details
------------------------+------------+--------
embeddings.position_ids | UNEXPECTED |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loaded 31741 chunks

In [ ]:
# Convert sto LangChain Documents for RAGAS
docs = []
for i, (text, metadata) in enumerate(zip(all_docs['documents'], all_docs['metadatas'])):
    docs.append(Document(page_content=text, metadata=metadata))

# Samples a subset; 31k chunks is way too many, RAGAS doesn't need all of them

docs_sample = random.sample(docs, min(200, len(docs)))
print(f"Sampled {len(docs_sample)} chunks for test generation")

Sampled 200 chunks for test generation

In [ ]:
#refactor
from openai import OpenAI; from ragas.llms import llm_factory;
#llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))

In [ ]:

#Sets up RAGAS generator to run overnight
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini"))#using best available model for a good price
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings
)

testset = generator.generate_with_langchain_docs(
    docs_sample,
    testset_size=50
)

# Saves results
df = testset.to_pandas()
df.to_csv(PROJECT_ROOT / "outputs" / "ragas_testset.csv", index=False)
print(f"Generated {len(df)} test cases")
df.head()

<positron-console-cell-9>:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
<positron-console-cell-9>:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
Applying SummaryExtractor: 100%|██████████| 178/178 [02:03<00:00,  1.44it/s]
Applying CustomNodeFilter:   0%|          | 0/200 [00:00<?, ?it/s]Node 3ef6de45-6786-4b31-b39b-7048d0ac37f5 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:   1%|          | 2/200 [00:01<02:17,  1.44it/s]Node 392d28c2-2f9a-4a04-91ae-af1332605488 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  18%|█▊        | 37/200 [00:24<01:26,  1.89it/s]Node 83b12662-245e-45de-844b-296a4aea034a does not have a summary. Skipping filtering.
Node 69597741-3d38-4df6-8852-ca8563d88739 does not have a summary. Skipping filtering.
Node 5ab2bc5f-97e9-4f3c-bec4-45ea81af96a0 does not have a summary. Skipping filtering.
Node 997119d0-4aea-41c1-94a1-a8775a7efcf3 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  19%|█▉        | 38/200 [00:33<03:06,  1.15s/it]Node d0f7d0a5-9307-4063-becb-8c51c88342b7 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  39%|███▉      | 78/200 [00:51<01:17,  1.58it/s]Node c66aa0dc-c082-4b47-a55c-45db73bbdc82 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  50%|█████     | 100/200 [01:02<00:56,  1.78it/s]Node 08f33647-a91a-4fba-8743-bca73307c6e3 does not have a summary. Skipping filtering.
Node 5f0487d9-1c40-4f44-b867-6ce057ef7863 does not have a summary. Skipping filtering.
Node 217a4697-6642-44c7-8b45-2d79e7676e7e does not have a summary. Skipping filtering.
Node b127008b-43ac-46cc-816d-33f1675ac25f does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  61%|██████    | 122/200 [01:13<00:35,  2.18it/s]Node 0526158d-b10f-4e7e-b6fe-e8445cbf555e does not have a summary. Skipping filtering.
Node 9fb6c662-a27b-4c77-9100-585292060d7d does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  69%|██████▉   | 138/200 [01:24<00:30,  2.02it/s]Node 6f0a0def-bcee-4989-a39f-9c760edf6968 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  70%|███████   | 141/200 [01:26<00:30,  1.93it/s]Node e700bcc0-5bf6-4ac7-b5ff-1965dd5da01a does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  72%|███████▎  | 145/200 [01:27<00:26,  2.10it/s]Node 6cf7215f-8f07-438e-9ec8-1312c1cdbd7c does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  84%|████████▎ | 167/200 [01:40<00:17,  1.93it/s]Node 0d44b28b-5bdd-4c38-b9eb-32975d6c8f94 does not have a summary. Skipping filtering.
Node 918466e7-ef09-4960-9500-97d6e1edd28c does not have a summary. Skipping filtering.
Node 3dc5df48-6cbc-4b64-8e4d-5ff44081bcd4 does not have a summary. Skipping filtering.
Applying CustomNodeFilter:  84%|████████▍ | 168/200 [01:48<00:53,  1.67s/it]Node 0408ca4c-e16e-4f93-b0a3-2bf7c7063127 does not have a summary. Skipping filtering.
Node ce1df328-3648-40fb-8663-fceb58be7236 does not have a summary. Skipping filtering.
Applying CustomNodeFilter: 100%|██████████| 200/200 [01:59<00:00,  1.67it/s]
Applying EmbeddingExtractor: 100%|██████████| 164/164 [01:34<00:00,  1.73it/s]
Applying ThemesExtractor: 100%|██████████| 186/186 [02:21<00:00,  1.32it/s]
Applying NERExtractor: 100%|██████████| 186/186 [02:16<00:00,  1.36it/s]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00,  4.99it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]
Generating personas: 100%|██████████| 3/3 [00:03<00:00,  1.09s/it]
Generating Scenarios: 100%|██████████| 3/3 [01:23<00:00, 27.67s/it]
Generating Samples: 100%|██████████| 51/51 [00:37<00:00,  1.35it/s]

Generated 51 test cases

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,Can you explain the significance of Scholz et ...,[steps for functional annotation are similar. ...,Scholz et al. 2012 is significant in the conte...,Marine Ecologist,MISSPELLED,LONG,single_hop_specific_query_synthesizer
1,What research did Siegelman H.W. contribute to...,"[Paerl H.W., Bland P.T., Bowles N.D. and Haiba...",Siegelman H.W. co-authored a study in 1983 tha...,Estuarine Ecologist,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
2,How is the AB28 primer utilized in the amplifi...,[rbcL-rbcS intergenic spacer to the first codo...,The AB28 primer is used to amplify the ITS1-5....,Estuarine Ecologist,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
3,What is Raphidiopsis mediterranea Skuja?,"[Miller (Pl. 2, Figs 5-8) . Geitler, 1925, p. ...",Raphidiopsis mediterranea Skuja is a species c...,Estuarine Ecologist,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
4,What distinguishes Centroceras hommersandii fr...,[Diagnosis. Differing from other species in th...,Centroceras hommersandii is distinguished from...,Marine Ecologist,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer

In [12]:
df.head()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,Can you explain the significance of Scholz et ...,[steps for functional annotation are similar. ...,Scholz et al. 2012 is significant in the conte...,Marine Ecologist,MISSPELLED,LONG,single_hop_specific_query_synthesizer
1,What research did Siegelman H.W. contribute to...,"[Paerl H.W., Bland P.T., Bowles N.D. and Haiba...",Siegelman H.W. co-authored a study in 1983 tha...,Estuarine Ecologist,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
2,How is the AB28 primer utilized in the amplifi...,[rbcL-rbcS intergenic spacer to the first codo...,The AB28 primer is used to amplify the ITS1-5....,Estuarine Ecologist,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
3,What is Raphidiopsis mediterranea Skuja?,"[Miller (Pl. 2, Figs 5-8) . Geitler, 1925, p. ...",Raphidiopsis mediterranea Skuja is a species c...,Estuarine Ecologist,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
4,What distinguishes Centroceras hommersandii fr...,[Diagnosis. Differing from other species in th...,Centroceras hommersandii is distinguished from...,Marine Ecologist,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer